#!/bin/bash
# you need creat exicutable this file using 
# chmod +x ./folder_clean_bash
# now just run: ./folder_clean_bash
# for using windows you just need to change .out to .exe file extantion in this file.
rm -r *.out && echo "cleared *.out files"
rm -r */*.out && echo "cleared */*.out files"
rm -r */*/*.out && echo "cleared */*/*.out files"
rm -r */*/*/*.out && echo "cleared */*/*/*.out files"
echo "Ignore errors when files are not thair it shows"
printf '\n\t Worktree is free with .out files..\n\n'
